export const SET_MY_SAVED_WORDS = 'SET_MY_SAVED_WORDS';
export const SAVE_WORD = 'SAVE_WORD';
export const SET_SEARCH_WORD = 'SET_SEARCH_WORD';
export const CHANGE_SEARCH_WORD = 'CHANGE_SEARCH_WORD';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';